"""Initialized all 3 tables

Revision ID: bc7c2419c642
Revises: 
Create Date: 2020-04-15 20:44:47.216696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7c2419c642'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_team_channel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vc_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice')
    op.drop_table('text')
    op.drop_table('online')
    # ### end Alembic commands ###
