"""Add multicolum unique constraint to the Online table

Revision ID: f22b055b001e
Revises: bc7c2419c642
Create Date: 2020-04-22 18:56:23.042402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f22b055b001e"
down_revision = "bc7c2419c642"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_user_per_day_constraint", "online", ["discord_user_id", "date"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_per_day_constraint", "online", type_="unique")
    # ### end Alembic commands ###
